# Generated by Django 5.1.6 on 2025-02-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, default='', upload_to='media\\store\\images\thumbimages')),
                ('category', models.CharField(choices=[('church', 'Church'), ('ministry', 'Ministry'), ('celebration', 'Celebration')], max_length=20)),
            ],
        ),
    ]
