# Generated by Django 5.1.6 on 2025-02-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verse_of_the_day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('englishname', models.CharField(max_length=20)),
                ('tamilname', models.CharField(max_length=20)),
                ('chapter', models.IntegerField()),
                ('versecount', models.IntegerField()),
                ('verse', models.TextField()),
                ('kjv', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='media/store/images/thumbimages'),
        ),
    ]
