# Generated by Django 5.1.6 on 2025-03-07 09:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0004_sermons'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermons',
            name='body',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sermons',
            name='googlemapcode',
            field=models.CharField(default='', max_length=1200),
        ),
        migrations.AlterField(
            model_name='sermons',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
