# Generated by Django 5.1.6 on 2025-03-07 10:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0005_sermons_body_sermons_googlemapcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermons',
            name='keywords',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
