# Generated by Django 5.1.6 on 2025-03-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0006_sermons_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verse_of_the_day',
            name='date',
            field=models.DateField(),
        ),
    ]
