# Generated by Django 5.1.6 on 2025-03-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0007_alter_verse_of_the_day_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, default='', upload_to='media/store/images/ministry')),
                ('category', models.CharField(choices=[('childrens ministry', 'Childrens Ministry'), ('youths ministry', 'Youths Ministry'), ('sports ministry', 'Sports Ministry'), ('mens ministry', 'Mens Ministry'), ('womens ministry', 'Womens Ministry')], max_length=20)),
            ],
        ),
    ]
