# Generated by Django 5.1.6 on 2025-03-11 05:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0008_ministry'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministry',
            name='body',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
