# Generated by Django 5.1.6 on 2025-03-11 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0009_ministry_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ministry',
            name='description',
        ),
    ]
