# Generated by Django 5.1.6 on 2025-03-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0010_remove_ministry_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
                ('roll', models.CharField(max_length=20)),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, default='', upload_to='media/store/images/teams')),
            ],
        ),
    ]
