# Generated by Django 5.1.6 on 2025-03-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0013_alter_team_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.CharField(max_length=150),
        ),
    ]
