# Generated by Django 5.1.6 on 2025-03-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0017_alter_team_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='', upload_to='media/store/images/teams')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=100)),
                ('calendarcode', models.CharField(default='', max_length=1200)),
            ],
        ),
        migrations.RenameField(
            model_name='sermons',
            old_name='googlemapcode',
            new_name='youtubecode',
        ),
    ]
