# Generated by Django 5.1.6 on 2025-03-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0018_event_rename_googlemapcode_sermons_youtubecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='media/store/images/event'),
        ),
    ]
