# Generated by Django 5.1.6 on 2025-03-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0019_alter_event_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Engaged', 'Engaged')], max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('emergency_phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('resident_name', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('door_number', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('church_transfer', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
                ('previous_church', models.CharField(blank=True, max_length=255, null=True)),
                ('ministry_interest', models.CharField(choices=[('Worship Team', 'Worship Team'), ('Youth Ministry', 'Youth Ministry'), ('Children’s Ministry', 'Children’s Ministry'), ('Prayer Group', 'Prayer Group'), ('Outreach & Evangelism', 'Outreach & Evangelism'), ('Media & Technical Support', 'Media & Technical Support'), ('Teaching & Discipleship', 'Teaching & Discipleship'), ('Ushering & Hospitality', 'Ushering & Hospitality')], max_length=50)),
                ('occupation', models.CharField(max_length=255)),
                ('agreement', models.BooleanField(default=False)),
            ],
        ),
    ]
