# Generated by Django 5.1.6 on 2025-03-17 12:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0021_usersstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchmember',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
