# Generated by Django 5.1.6 on 2025-03-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0022_churchmember_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchmember',
            name='profile_image',
            field=models.ImageField(blank=True, default='', upload_to='media/store/images/profile'),
        ),
    ]
