# Generated by Django 5.1.6 on 2025-03-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0025_alter_certificate_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate',
            field=models.FileField(upload_to='media/store/pdf/certificates'),
        ),
    ]
