# Generated by Django 5.1.7 on 2025-03-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0026_alter_certificate_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificatestatus',
            field=models.IntegerField(default=0),
        ),
    ]
